http:
  routers:
    monitor-prometheus:
      rule: Host(`prometheus.econictek.com`)
      entryPoints:
        - websecure
      priority: 50
      tls:
        certResolver: le
        domains:
          - main: econictek.com
            sans:
              - "*.econictek.com"
      service: monitor-prometheus

    monitor-loki:
      rule: Host(`loki.econictek.com`)
      entryPoints:
        - websecure
      priority: 50
      tls:
        certResolver: le
        domains:
          - main: econictek.com
            sans:
              - "*.econictek.com"
      service: monitor-loki

    monitor-grafana:
      rule: Host(`grafana.econictek.com`)
      entryPoints:
        - websecure
      priority: 50
      tls:
        certResolver: le
        domains:
          - main: econictek.com
            sans:
              - "*.econictek.com"
      service: monitor-grafana

    tenant-admin:
      rule: Host(`admin.econictek.com`)
      entryPoints:
        - websecure
      tls:
        certResolver: le
        domains:
          - main: econictek.com
            sans:
              - "*.econictek.com"
      service: store-api

    store-api:
      rule: HostRegexp(`{tenant:[a-z0-9-]+}.econictek.com`) && PathPrefix(`/api`)
      entryPoints:
        - websecure
      priority: 10
      middlewares:
        - strip-api-prefix
      tls:
        certResolver: le
        domains:
          - main: econictek.com
            sans:
              - "*.econictek.com"
      service: store-api

    store-web:
      rule: HostRegexp(`{tenant:[a-z0-9-]+}.econictek.com`)
      entryPoints:
        - websecure
      priority: 1
      tls:
        certResolver: le
        domains:
          - main: econictek.com
            sans:
              - "*.econictek.com"
      service: store-web

  middlewares:
    strip-api-prefix:
      stripPrefix:
        prefixes:
          - /api

  services:
    monitor-prometheus:
      loadBalancer:
        servers:
          - url: http://prometheus:9090

    monitor-loki:
      loadBalancer:
        servers:
          - url: http://loki:3100

    monitor-grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000

    store-api:
      loadBalancer:
        servers:
          - url: http://econictek-retail-api:8000
    store-web:
      loadBalancer:
        servers:
          - url: http://econictek-retail-fe:3000
